# Generated by Django 3.0.2 on 2020-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200107_2151'),
        ('booksList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='books',
        ),
        migrations.AddField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
