# Generated by Django 3.0.2 on 2020-01-07 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200107_2151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksList', '0002_auto_20200107_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(blank=True, related_name='books', to='books.Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
