# Generated by Django 3.0.2 on 2020-01-07 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cover_art', models.ImageField(upload_to='book_covers/')),
                ('category', models.CharField(choices=[('SO', 'Social'), ('CU', 'Cultural'), ('BI', 'Biological')], default='SO', max_length=2)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('amazon_link', models.CharField(max_length=128)),
            ],
        ),
    ]
