# Generated by Django 3.0.2 on 2020-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200107_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(blank=True, upload_to='book_covers/'),
        ),
    ]
