# Generated by Django 3.0.2 on 2020-01-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200107_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='have_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
